# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4fa74aa8a3a58c211f098c19ecc958bd97a63cd00d6f62fabc99759026161cf0fa14bce7f69cd9a8373aacdbec5d71213546a2b2f443bfcc833f641fb590aef

test:
  secret_key_base: d5341772b49414ae543b80c3e1a602d0cdc4927a698346290e3db23f8b17672644471b09025e8c477ebcccde5e847d6741efedcca9dbce8f4fc555dfcc5f4d39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
